### ISSUE TITLE
documentation is wrong

### ISSUE THREAD

**Issue by Nahnja** [arximboldi/heterarchy#2]
The example given in your documentation is wrong.

``` coffeescript
{multi} = require 'heterarchy'

class A
    method: -> "A"

class B extends A
    method: -> "B > #{super}"

class C extends A
    method: -> "C > #{super}"

class D extends multi B, C
    method: -> "D > #{super}"
```

Calling method on a D instance does not return the string `D > C > B > A`. 
Instead it returns `D > B > C > A`.

**Comment by arximboldi** [comment]
Good catch! I'll fix ASAP, thanks!

**Comment by arximboldi** [comment]
Addressed!

I also updated the image with something from this related project of mine: https://github.com/arximboldi/cooper

I hope you like it.

**Comment by Nahnja** [comment]
I do!
